create TABLE ${flyway:defaultSchema}.footballers
(
    footballer_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name          VARCHAR(255)    NOT NULL,
    last_name           VARCHAR(255)    NOT NULL,
    gender              VARCHAR(255)    NOT NULL,
    birth_date          VARCHAR(255)    NOT NULL,
    team_name           VARCHAR(255)    NOT NULL,
    footballer_country  VARCHAR(255)    NOT NULL,
    CONSTRAINT pk_footballers PRIMARY KEY (footballer_id)
);